var brightness = document.getElementById('brightnessIcon')
var ChangeMenu = document.getElementById('change')
var ToggleHeader = document.getElementById('ToggleHeader')
var searchIcon = document.getElementById('searchIcon')
var AsideChange = document.getElementById('AsideChange')
var shadowToggle = document.getElementById('shadowToggle')
var shadowToggle2 = document.getElementById('shadowToggle2')
var shadowToggle3 = document.getElementById('shadowToggle3')
var firstBorder = document.getElementById('firstBorder')
var SecondBorder = document.getElementById('SecondBorder')
//
brightness.addEventListener('click', () => {
  ChangeMenu.classList.toggle('dark-mode')
  ToggleHeader.classList.toggle('dark-mode')
  searchIcon.classList.toggle('dark-color')
  AsideChange.classList.toggle('dark-mode')
  shadowToggle.classList.toggle('shadow')
  shadowToggle2.classList.toggle('shadow')
  shadowToggle3.classList.toggle('shadow')
  firstBorder.classList.toggle('shadow')
  SecondBorder.classList.toggle('shadow')
})
